/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeePayrollService;

import org.junit.Test;

import com.bridgelabz.employeepayrollservice.EmployeePayrollService;

import static org.junit.Assert.*;

public class EmployeePayrollServiceTest {
}
